### ISSUE TITLE
IntelBluetoothFirmware

### ISSUE THREAD

**Issue by daninow** [haitrvnvn/Hackintosh-MSI-GL63-8RD#1]
Everything works fine also on my MSI GL63 8RD, but, have you checked the IntelBluetoothFirmware?
https://github.com/zxystd/IntelBluetoothFirmware

**Comment by haitrvnvn** [comment]
Sorry for my English!
You need replace Intel Wifi - Bluetooth card (Intel wifi card not supported in hackintosh)
my suggestions it's BCM94350ZAE(20$~25$)

**Comment by daninow** [comment]
@haitrvnvn really thank you!
